/*
 * format_converter.h
 *
 * Header file for the SynchDB format converter module
 *
 * This module provides structures and functions for processing
 * database change events in Debezium (DBZ) format and converting
 * them to a format suitable for SynchDB.
 *
 * Key components:
 * - Structures for representing DDL (Data Definition Language) events
 * - Structures for representing DML (Data Manipulation Language) events
 * - Functions for processing and converting DBZ change events
 *
 * Copyright (c) Hornetlabs Technology, Inc.
 * 
 */

#ifndef SYNCHDB_FORMAT_CONVERTER_H_
#define SYNCHDB_FORMAT_CONVERTER_H_

#include "utils/hsearch.h"
#include "nodes/pg_list.h"
#include "utils/jsonb.h"
#include "executor/replication_agent.h"
#include "synchdb/synchdb.h"

/* constants */
#define RULEFILE_DATATYPE_TRANSFORM 1
#define RULEFILE_OBJECTNAME_TRANSFORM 2
#define RULEFILE_EXPRESSION_TRANSFORM 3

/* structure to hold possible time representations in DBZ engine */
typedef enum _timeRep
{
	TIME_UNDEF = 0,
	TIME_DATE,				/* number of days since epoch */
	TIME_TIME,				/* number of milliseconds since epoch */
	TIME_ZONEDTIME,			/* number of milliseconds since epoch with timezone */
	TIME_MICROTIME,			/* number of microseconds since midnight */
	TIME_NANOTIME,			/* number of nanoseconds since midnight */
	TIME_TIMESTAMP,			/* number of milliseconds since epoch */
	TIME_MICROTIMESTAMP,	/* number of microseconds since epoch */
	TIME_NANOTIMESTAMP,		/* number of nanoseconds since epoch */
	TIME_ZONEDTIMESTAMP,	/* string representation of timestamp with timezone */
	TIME_MICRODURATION,	/* duration expressed in microseconds */
	DATA_VARIABLE_SCALE,	/* indication if scale is variable (for oracle) */
	DATA_GEOMETRY,			/* indication of geometry data */
	DATA_ENUM,				/* indication of enum data */
	DATA_UUID,				/* indication of uuid data */
	DATA_JSON,				/* indication of json data */
	DATA_XML,				/* indication of xml data */
	DATA_BITS,				/* indication of bits data */
	DATA_POINT,				/* indication of points data */
	} TimeRep;

/* Structure to represent a column in a DDL event */
typedef struct dbz_ddl_column
{
	char * name;
	int length;
	bool optional;
	int position;
	char * typeName;
	char * enumValues;
	char * charsetName;
	bool autoIncremented;
	char * defaultValueExpression;
	int scale;
} DBZ_DDL_COLUMN;

/* another alias to the same DDL COLUMN struct for clarity */
typedef DBZ_DDL_COLUMN OLR_DDL_COLUMN;

/* Structure to represent a DDL event */
typedef struct dbz_ddl
{
	char * id;
	DdlType type;
	AlterSubType subtype;
	char * primaryKeyColumnNames;
	char * constraintName;
	List * columns;			/* list of DBZ_DDL_COLUMN */
	unsigned long long dbz_ts_ms;	/* time(ms) when this DDL is processed by DBZ */
	unsigned long long src_ts_ms;	/* time(ms) when this DDL is generated by source database */
} DBZ_DDL;

/* another alias to the same DDL struct for clarity */
typedef DBZ_DDL OLR_DDL;

typedef struct
{
	char name[NAMEDATALEN];
	Oid oid;
	int position;
	int typemod;
	bool ispk;
	char typcategory;
	bool typispreferred;
	char typname[NAMEDATALEN];
} NameOidEntry;

typedef struct
{
	char name[NAMEDATALEN];
	int jsonpos;
	int dbztype;
	TimeRep timerep;
	int scale;
} NameJsonposEntry;

/* Structure to represent a column value in a DML event */
typedef struct dbz_dml_column_value
{
	char * name;	/* name of the column field */
	char * remoteColumnName;	/* original column name from remote server */
	char * value;	/* expressed as string as taken from json */
	Oid datatype;	/* data type Oid as defined by PostgreSQL */
	int position;	/* position of this column value, start from 1 */
	int scale;		/* location of decimal point - decimal type only */
	int timerep;	/* how dbz represents time related fields */
	int typemod;	/* extra data type modifier */
	bool ispk;		/* indicate if this column is a primary key*/
	int dbztype;	/* data literal type as defined by dbz */
	char typcategory;	/* type category defined by pg */
	bool typispreferred;	/* wether type category is preferred by pg */
	char * typname;		/* the name of the data type */
} DBZ_DML_COLUMN_VALUE;

/* Structure to represent a DML event */
typedef struct dbz_dml
{
	char op;
	char * schema;
	char * table;
	char * remoteObjectId;		/* db.schema.table or db.table on remote side */
	char * mappedObjectId;		/* schema.table, or just table on PG side */
	Oid tableoid;
	int natts;					/* number of columns of this pg table */
	List * columnValuesBefore;	/* list of DBZ_DML_COLUMN_VALUE */
	List * columnValuesAfter;	/* list of DBZ_DML_COLUMN_VALUE */
	unsigned long long dbz_ts_ms;	/* time(ms) when this DML is processed by DBZ */
	unsigned long long src_ts_ms;	/* time(ms) when this DML is generated by source database */
} DBZ_DML;

/* another alias to the same DML struct for clarity */
typedef DBZ_DML OLR_DML;

/* dml cache structure */
typedef struct dataCacheKey
{
	char schema[SYNCHDB_CONNINFO_DB_NAME_SIZE];
	char table[SYNCHDB_CONNINFO_DB_NAME_SIZE];
} DataCacheKey;
typedef struct dataCacheEntry
{
	DataCacheKey key;
	TupleDesc tupdesc;
	Oid tableoid;
	HTAB * typeidhash;
	HTAB * namejsonposhash;
	int natts;
} DataCacheEntry;

typedef struct datatypeHashKey
{
	char extTypeName[SYNCHDB_DATATYPE_NAME_SIZE];
	bool autoIncremented;
} DatatypeHashKey;

typedef struct datatypeHashEntry
{
	DatatypeHashKey key;
	char pgsqlTypeName[SYNCHDB_DATATYPE_NAME_SIZE];
	int pgsqlTypeLength;
} DatatypeHashEntry;

typedef struct objMapHashKey
{
	char extObjName[SYNCHDB_OBJ_NAME_SIZE];
	char extObjType[SYNCHDB_OBJ_TYPE_SIZE];
} ObjMapHashKey;

typedef struct objMapHashEntry
{
	ObjMapHashKey key;
	char pgsqlObjName[SYNCHDB_OBJ_NAME_SIZE];
} ObjMapHashEntry;

typedef struct transformExpressionHashKey
{
	char extObjName[SYNCHDB_OBJ_NAME_SIZE];
} TransformExpressionHashKey;

typedef struct transformExpressionHashEntry
{
	TransformExpressionHashKey key;
	char pgsqlTransExpress[SYNCHDB_TRANSFORM_EXPRESSION_SIZE];
} TransformExpressionHashEntry;

/* Function prototypes */
ConnectorType fc_get_connector_type(const char * connector);
void fc_initFormatConverter(ConnectorType connectorType);
void fc_deinitFormatConverter(ConnectorType connectorType);
void fc_initDataCache(void);
void fc_deinitDataCache(void);
void fc_resetDataCache(void);
bool fc_load_objmap(const char * name, ConnectorType connectorType);
char * escapeSingleQuote(const char * in, bool addquote);
int getPathElementString(Jsonb * jb, char * path, StringInfoData * strinfoout, bool removequotes);
void remove_double_quotes(StringInfoData * str);
bool find_exact_string_match(const char * line, const char * wordtofind);
char * transform_object_name(const char * objid, const char * objtype);
void splitIdString(char * id, char ** db, char ** schema, char ** table, bool usedb);
int list_sort_cmp(const ListCell *a, const ListCell *b);
PG_DDL * convert2PGDDL(DBZ_DDL * dbzddl, ConnectorType type);
void updateSynchdbAttribute(DBZ_DDL * dbzddl, PG_DDL * pgddl, ConnectorType conntype, const char * name);
PG_DML * convert2PGDML(DBZ_DML * dbzdml, ConnectorType type);
bool fc_translate_datatype(ConnectorType connectorType,
		const char * ext_datatype, int * ext_length, int * ext_scale,
		char ** pg_datatype, int * pg_datatype_len);
void fc_normalize_name(LetterCasingStrategy strategy, char * name, int len);

#endif /* SYNCHDB_FORMAT_CONVERTER_H_ */
