services:
  db:
    image: postgres:18.1
    container_name: postgres
    shm_size: 256mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    command:
      - postgres
      - "-c"
      - "wal_level=logical"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    networks:
      - synchdbnet

networks:
  synchdbnet:
    name: synchdbnet
    driver: bridge
    internal: true

